---
- hosts: virtuaalikone
  remote_user: adminuser
  sudo: yes
  tasks:
    - name: what is a jail
      jail:
        jail_dir: /var/jail
        commands:
          - /bin/bash
          - /bin/echo
        dirs:
          - /usr/lib/python2.7
