---
- hosts: virtuaalikone
  remote_user: adminuser
  sudo: yes
  tasks:
    - name: what is a jail
      jail:
        jail_folder: /var/jail
        commands:
          - /bin/bash
          - /bin/ls
